apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-game-room

resources:
    - ../../base
    - atlas-db-user.yaml
    - configmaps.yaml
    - ingress.yaml
    - middlewares.yaml
    - mongodb-atlas-service-entry.yaml
    - secrets.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: game-room
          component: api

generatorOptions:
    disableNameSuffixHash: true
